### ISSUE TITLE
Item x0

### ISSUE THREAD

**Issue by lvp11** [ESX-Org/esx_addoninventory#11]
Hey!

After removing items from stock, i get the item name x0, and it keeps on the list, with 0 quantity.
Any ideas to remove this items?
Example:
![image](https://user-images.githubusercontent.com/47780889/57587536-87b62880-74dc-11e9-8795-acf1280d0e3a.png)

Thanks!

**Comment by Xteaw** [comment]
Same

**Comment by Zeedfy** [comment]
me too, any solution?

**Comment by Memor1esleyy** [comment]
any solution?
