### ISSUE TITLE
Item Count x0

### ISSUE THREAD

**Issue by SNIKRS** [ESX-Org/esx_addoninventory#18]
Exemple, i add 1 weed in my store and then taking it back to my inv, i will get 0x weed in my store. And sometimes when i add weeds to my store and then disconnecting and reconnecting i get 0x weed

**Comment by hifzi** [comment]
change in your function stocks menu, 

example  for esx_policejob:
 `function OpenGetStocksMenu()
	ESX.TriggerServerCallback('esx_policejob:getStockItems', function(items)
		local elements = {}
for i=1, #items, 1 do
			table.insert(elements, {
				label = 'x' .. items[i].count .. ' ' .. items[i].label,
				value = items[i].name
			})
		end
...
....`

change to 

`function OpenGetStocksMenu()
	ESX.TriggerServerCallback('esx_policejob:getStockItems', function(items)
		local elements = {}

		for i=1, #items, 1 do
			if items[i].count ~= 0 then
			table.insert(elements, {
				label = 'x' .. items[i].count .. ' ' .. items[i].label,
				value = items[i].name
			})
			end
		end`
