### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Aleksandres** [ESX-Org/esx_addoninventory#3]
Error running system event handling function for resource esx_addoninventory: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/main.lua:47: table index is nil
stack traceback:
	server/main.lua:47: in upvalue 'handler'
	citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:173>
stack traceback:
	[C]: in function 'error'
	citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
	citizen:/scripting/lua/scheduler.lua:173: in function <citizen:/scripting/lua/scheduler.lua:138>
hitch warning: frame time of 1646 milliseconds

**Comment by Aleksandres** [comment]
There was a wrong encoding in the database, the question was settled.

**Comment by Dinamicka** [comment]
can help me? i have the same issue

**Comment by galihwicaak** [comment]
Error resuming coroutine: @esx_addoninventory/server/main.lua:70: 'for' limit must be a number 
stack traceback: 
@esx_addoninventory/server/main.lua:70: in function 'GetInventory' 
@esx_addoninventory/server/main.lua:102: in upvalue 'handler' 
citizen:/scripting/lua/scheduler.lua:169: in function <citizen:/scripting/lua/scheduler.lua:168>

**Comment by SrConflictivo** [comment]
getting the same error, did u solve it?
